# Generated by Django 3.2 on 2021-07-02 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('fee', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('IT', 'IT'), ('CIVIL', 'CIVIL')], default='CSE', max_length=5, verbose_name='What is your department')),
                ('c_name', models.CharField(choices=[('CSE-Python', 'CSE-Python'), ('CSE-R and software Development', 'CSE-R and software Development'), ('CSE-Fundamentals of java programming', 'CSE-Fundamentals of java programming'), ('IT-Web Development or Full Stack Developer', 'IT-Web Development or Full Stack Developer'), ('IT-Google Cloud Platform Architecture', 'IT-Google Cloud Platform Architecture'), ('IT-JavaScript', 'IT-JavaScript'), ('EEE-Electrical Safety Course', 'EEE-Electrical Safety Course'), ('EEE-Equipment Selection Specialisation', 'EEE-Equipment Selection Specialisation'), ('EEE-Plant Earthing course', 'EEE-Plant Earthing course'), ('CIVIL-Bridge Engineering', 'CIVIL-Bridge Engineering'), ('CIVIL-Irrigation Engineering', 'CIVIL-Irrigation Engineering'), ('CIVIL-Hydraulic Engineering', 'CIVIL-Hydraulic Engineering')], default='Python', max_length=100, verbose_name='Which course do you want to take up?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
